import { publicClient } from '@/lib/viem/client';

/**
 * Benchmarks the signature verification logic.
 * Run this in HQ to ensure cryptographic handshake performance.
 */
export async function benchmarkVerification(iterations: number = 100) {
  const testAddress = '0x5e05ffd981fc497a12fcce2c0d87767f1e794c30';
  const testMessage = 'Benchmark message for baseFM';
  // Example valid signature for testing (this would be generated by a wallet)
  const testSignature = '0x...'; 

  console.time('SignatureVerificationBenchmark');
  for (let i = 0; i < iterations; i++) {
    // Note: This is a placeholder for actual benchmarking logic
    // In a real run, we would use a pre-signed message
    await publicClient.verifyMessage({
      address: testAddress as `0x${string}`,
      message: testMessage,
      signature: testSignature as `0x${string}`,
    });
  }
  console.timeEnd('SignatureVerificationBenchmark');
}

export function isValidWalletAddress(address: string): boolean {
  return /^0x[a-fA-F0-9]{40}$/.test(address);
}

export function normalizeWalletAddress(address: string): string {
  return address.toLowerCase();
}

export async function verifyWalletSignature(
  address: string,
  message: string,
  signature: string
): Promise<boolean> {
  if (!isValidWalletAddress(address)) return false;
  
  try {
    // publicClient.verifyMessage handles EOA + EIP-1271 (deployed smart
    // wallets) + ERC-6492 (counterfactual/undeployed smart wallets), which
    // is required for Coinbase Smart Wallet users.
    const isValid = await publicClient.verifyMessage({
      address: address as `0x${string}`,
      message,
      signature: signature as `0x${string}`,
    });
    return isValid;
  } catch (error) {
    console.error('Error verifying wallet signature:', error);
    return false;
  }
}

export function createAuthMessage(nonce: string): string {
  return `Sign this message to authenticate with baseFM.\n\nNonce: ${nonce}`;
}

export type StreamAction = 'setup' | 'stop';

export function createStreamActionMessage(
  action: StreamAction,
  streamId: string,
  nonce: string,
  timestamp: string
): string {
  const verb = action === 'setup' ? 'Generate credentials for' : 'Stop';
  return `${verb} baseFM stream ${streamId}\nNonce: ${nonce}\nTimestamp: ${timestamp}`;
}

export function generateNonce(): string {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  
  const array = new Uint8Array(16);
  crypto.getRandomValues(array);
  return Array.from(array, byte => byte.toString(16).padStart(2, '0')).join('');
}
